name: udevs_tz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:

  #Request to API
  dio: ^5.5.0+1

  #State Manegment
  flutter_bloc: ^8.1.6

  #Equality
  equatable: ^2.0.5

  #Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3

  #Get location
  geolocator: ^12.0.0

  #Notification
  flutter_local_notifications: ^17.2.1+1

  #Locator
  get_it: ^7.7.0

  #Log request
  logger: ^2.3.0

  #Date Format
  intl: ^0.19.0

  #UI
  zoom_tap_animation: ^1.1.0
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1

  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/poppins/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700


